print ("Hello, Dcoder!")
print ("not:The following program is madeby doctor so dont")
print ("worry, the results will be 100% accurate, let's begin")


import random
import time
print("#############################################")
time.sleep(1)
print("\n        Hello, my name is Dr. APOORV\n")
time.sleep(1)
print ("           I'm a Doctor \n")
time.sleep(2)
print("I'm here for checking rather you have covid-19 \n or no\n")
time.sleep(1.5)
print("\n   Let's get in the check-up🧐\n")
time.sleep(1.5)
name = str(input("Tell me your first name please : "))
time.sleep(1)
print("\n    That's a good name,",name)
time.sleep(1)
adhar = int(input("\n plz enter your adhar number\n - "))
time.sleep(1)
age = int(input("\nOk how old are you?\n - "))
time.sleep(1)
print("ok now let's check some symptoms..\n")
time.sleep(1)
cough = str(input("\nSo,Do you feel dry cough?(y/n)\n - "))
fever = str(input("\nDo you have fever?(y/n)\n - "))
tired = str(input("\nDo you feel tiredness at all?(y/n)\n - "))
breath = str(input("\nDo you have difficulty in breathing?(y/n)\n - "))

if cough=="y" and fever=="y" and tired=="y" and breath=="y":
  print("\nhmm.. Don't engage with people.. Contact your doctor.. \nplease call _ 011-23978046 \nAnd follow some steps to avoid spreading it.")
elif cough=="n" and fever=="n" and tired=="n" and breath=="n":
    print(" \nPick up a pillow and jump to bed 🛌\n    No one is gonna harm you😅 \n Follow some steps to avoid getting it..")
else:
  print("\n          Ok, don't worry it's normal",name,"\n        Take care of yourself \n           And follow following steps")
time.sleep(2)
print("\nYou can protect yourself and \nhelp prevent spreading the virus to others \nif you:\n")
time.sleep(2)
print("Do\nWash your hands regularly \nfor 20 seconds, with soap and water or\nalcohol-based hand rub\n")
time.sleep(2)
print("Cover your nose and mouth \nwith a disposable tissue or flexed elbow\n when you cough or sneeze\n")
time.sleep(2)
print("Avoid close contact (1 meter or 3 feet) \nwith people who are unwell \n")
time.sleep(2)
print("Stay home and self-isolate from others\n in the household if you feel unwell\n")
time.sleep(2)
print("Don't\nTouch your eyes, nose, \nor mouth if your hands are not clean\n")
print("###############################################")
print("thank you for choosing my program")
print("Stay Safe. Stay Healthy, see you soon",name)